publish_to: 'https://pub.dev'
name: cross_scroll
description: A CrossScroll is a flutter Package that permits it’s child views to be scrolled vertically and Horizontally.

version: 0.0.76
homepage: https://github.com/Mehrankhan-METRA-RGB/cross_scroll
repository: https://github.com/Mehrankhan-METRA-RGB/cross_scroll
issue_tracker: https://github.com/Mehrankhan-METRA-RGB/cross_scroll/issues
documentation: https://cross_scroll.metra.dev
license: MIT
#authors:
#  - 'm.jan9396@gmail.com'
#  - '+923219195952'



environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0
#  analyzer: ^3.2.0
#  lints: ^1.0.1


flutter:
