name: cross_scroll
description: A CrossScroll is a flutter Package that permits it’s child views to be scrolled vertically and Horizontally.

version: 0.0.75
homepage: https://github.com/Mehrankhan-METRA-RGB/cross_scroll
#authors:
#  - 'm.jan9396@gmail.com'
#  - '+923219195952'



environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0
#  analyzer: ^3.2.0
#  lints: ^1.0.1


flutter:
